#!/bin/bash

# Collect all the SQL files from every result directory

# SGE Parameters
## Name
#$ -N collect_lidc

## working directory
#$ -cwd

## Export variables
#$ -V

## Logs -- to /dev/null
# -o /home/sgeadmin/logs/
#$ -j yes
#$ -e /dev/null
#$ -o /dev/null


# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -uo pipefail
IFS=$'\n\t'
shopt -s nullglob

# Some variables
if [ `uname` = 'Linux' ]; then

    # Linux paths
    export PATH=$PATH:$JAVA_HOME/bin:/software/bin:/software/python
else
    # Mac path
    PATH=`pwd`/build/install/LIDCTooling/bin:$PATH
    PATH=`pwd`/../ChestImagingPlatform/build/CIP-build/bin/:`pwd`/python/:${PATH}
fi

# in 'main' we can reference functions later in the script
main() {
    
    # Database name
    DB=${1:-lidc.db}
    DB=$(fullPath $DB)

    printf "Collect LIDC Results\n"
    createDB
    printf "Created database: %s\n" %DB
    wd=$(pwd)
    printf "Indexing reads"
    # Index the reads
    for dir in segmented/*; do
        if [[ -e $dir/results.sql ]]; then
            printf "."
            sqlite3 $DB < $dir/results.sql
            if [[ $? -ne 0 ]]; then
                printf "\n\n====\nFailed:\n$dir\n====\n\n" $dir
            fi

        fi
    done
    printf "\n"
    
}

function createDB {
# Create the database
sqlite3 $DB <<EOF
create table if not exists series (
  uid text primary key,
  series_instance_uid text,
  study_instance_uid text,
  patient_name text,
  patient_id text,
  manufacturer text,
  manufacturer_model_name text,
  patient_sex text,
  patient_age text,
  ethnic_group text,
  contrast_bolus_agent text,
  body_part_examined text,
  scan_options text,
  slice_thickness float,
  kvp float,
  data_collection_diameter float,
  software_versions text,
  reconstruction_diameter float,
  gantry_detector_tilt float,
  table_height float,
  rotation_direction text,
  exposure_time float,
  xray_tube_current float,
  exposure float,
  convolution_kernel text,
  patient_position text,
  image_position_patient text,
  image_orientation_patient text,
  filename text );

create table if not exists reads (
  uid text primary key,
  filename text,
  id text
);

create table if not exists nodules (
  uid text primary key,
  read_uid text,
  normalized_nodule_id int,
  id text,
  centroid text,
  centroidLPS text,
  point_count int,
  label_value int,
  subtlety int,
  internalStructure int,
  calcification int,
  sphericity int,
  margin int,
  lobulation int,
  spiculation int,
  texture int,
  malignancy int  
);

create table if not exists measures (
  uid text primary key,
  nodule_uid text,
  read_uid text,
  path text,
  algorithm text,
  command_line text,
  false_negative_error float,
  dice_coefficient float,
  volume_similarity float,
  false_positive_error float,
  mean_overlap float,
  union_overlap float,
  jaccard_coefficient float,
  hausdorff_distance float,
  average_hausdorff_distance float
);

create table if not exists errors (
  uid text primary key,
  path text,
  name text,
  log text,
  text text
);

create table if not exists features (
  uid text primary key,
  nodule_uid text,
  read_uid text,
  algorithm text,
  LoG_sigma_05_Energy real,
  LoG_sigma_05_Entropy real,
  LoG_sigma_05_Kurtosis real,
  LoG_sigma_05_Maximum real,
  LoG_sigma_05_Mean real,
  LoG_sigma_05_MeanDeviation real,
  LoG_sigma_05_Median real,
  LoG_sigma_05_Minimum real,
  LoG_sigma_05_Range real,
  LoG_sigma_05_RootMeanSquared real,
  LoG_sigma_05_Skewness real,
  LoG_sigma_05_StandardDeviation real,
  LoG_sigma_05_TotalEnergy real,
  LoG_sigma_05_Uniformity real,
  LoG_sigma_05_Variance real,
  LoG_sigma_10_Energy real,
  LoG_sigma_10_Entropy real,
  LoG_sigma_10_Kurtosis real,
  LoG_sigma_10_Maximum real,
  LoG_sigma_10_Mean real,
  LoG_sigma_10_MeanDeviation real,
  LoG_sigma_10_Median real,
  LoG_sigma_10_Minimum real,
  LoG_sigma_10_Range real,
  LoG_sigma_10_RootMeanSquared real,
  LoG_sigma_10_Skewness real,
  LoG_sigma_10_StandardDeviation real,
  LoG_sigma_10_TotalEnergy real,
  LoG_sigma_10_Uniformity real,
  LoG_sigma_10_Variance real,
  LoG_sigma_15_Energy real,
  LoG_sigma_15_Entropy real,
  LoG_sigma_15_Kurtosis real,
  LoG_sigma_15_Maximum real,
  LoG_sigma_15_Mean real,
  LoG_sigma_15_MeanDeviation real,
  LoG_sigma_15_Median real,
  LoG_sigma_15_Minimum real,
  LoG_sigma_15_Range real,
  LoG_sigma_15_RootMeanSquared real,
  LoG_sigma_15_Skewness real,
  LoG_sigma_15_StandardDeviation real,
  LoG_sigma_15_TotalEnergy real,
  LoG_sigma_15_Uniformity real,
  LoG_sigma_15_Variance real,
  LoG_sigma_20_Energy real,
  LoG_sigma_20_Entropy real,
  LoG_sigma_20_Kurtosis real,
  LoG_sigma_20_Maximum real,
  LoG_sigma_20_Mean real,
  LoG_sigma_20_MeanDeviation real,
  LoG_sigma_20_Median real,
  LoG_sigma_20_Minimum real,
  LoG_sigma_20_Range real,
  LoG_sigma_20_RootMeanSquared real,
  LoG_sigma_20_Skewness real,
  LoG_sigma_20_StandardDeviation real,
  LoG_sigma_20_TotalEnergy real,
  LoG_sigma_20_Uniformity real,
  LoG_sigma_20_Variance real,
  LoG_sigma_25_Energy real,
  LoG_sigma_25_Entropy real,
  LoG_sigma_25_Kurtosis real,
  LoG_sigma_25_Maximum real,
  LoG_sigma_25_Mean real,
  LoG_sigma_25_MeanDeviation real,
  LoG_sigma_25_Median real,
  LoG_sigma_25_Minimum real,
  LoG_sigma_25_Range real,
  LoG_sigma_25_RootMeanSquared real,
  LoG_sigma_25_Skewness real,
  LoG_sigma_25_StandardDeviation real,
  LoG_sigma_25_TotalEnergy real,
  LoG_sigma_25_Uniformity real,
  LoG_sigma_25_Variance real,
  LoG_sigma_30_Energy real,
  LoG_sigma_30_Entropy real,
  LoG_sigma_30_Kurtosis real,
  LoG_sigma_30_Maximum real,
  LoG_sigma_30_Mean real,
  LoG_sigma_30_MeanDeviation real,
  LoG_sigma_30_Median real,
  LoG_sigma_30_Minimum real,
  LoG_sigma_30_Range real,
  LoG_sigma_30_RootMeanSquared real,
  LoG_sigma_30_Skewness real,
  LoG_sigma_30_StandardDeviation real,
  LoG_sigma_30_TotalEnergy real,
  LoG_sigma_30_Uniformity real,
  LoG_sigma_30_Variance real,
  LoG_sigma_35_Energy real,
  LoG_sigma_35_Entropy real,
  LoG_sigma_35_Kurtosis real,
  LoG_sigma_35_Maximum real,
  LoG_sigma_35_Mean real,
  LoG_sigma_35_MeanDeviation real,
  LoG_sigma_35_Median real,
  LoG_sigma_35_Minimum real,
  LoG_sigma_35_Range real,
  LoG_sigma_35_RootMeanSquared real,
  LoG_sigma_35_Skewness real,
  LoG_sigma_35_StandardDeviation real,
  LoG_sigma_35_TotalEnergy real,
  LoG_sigma_35_Uniformity real,
  LoG_sigma_35_Variance real,
  LoG_sigma_40_Energy real,
  LoG_sigma_40_Entropy real,
  LoG_sigma_40_Kurtosis real,
  LoG_sigma_40_Maximum real,
  LoG_sigma_40_Mean real,
  LoG_sigma_40_MeanDeviation real,
  LoG_sigma_40_Median real,
  LoG_sigma_40_Minimum real,
  LoG_sigma_40_Range real,
  LoG_sigma_40_RootMeanSquared real,
  LoG_sigma_40_Skewness real,
  LoG_sigma_40_StandardDeviation real,
  LoG_sigma_40_TotalEnergy real,
  LoG_sigma_40_Uniformity real,
  LoG_sigma_40_Variance real,
  LoG_sigma_45_Energy real,
  LoG_sigma_45_Entropy real,
  LoG_sigma_45_Kurtosis real,
  LoG_sigma_45_Maximum real,
  LoG_sigma_45_Mean real,
  LoG_sigma_45_MeanDeviation real,
  LoG_sigma_45_Median real,
  LoG_sigma_45_Minimum real,
  LoG_sigma_45_Range real,
  LoG_sigma_45_RootMeanSquared real,
  LoG_sigma_45_Skewness real,
  LoG_sigma_45_StandardDeviation real,
  LoG_sigma_45_TotalEnergy real,
  LoG_sigma_45_Uniformity real,
  LoG_sigma_45_Variance real,
  LoG_sigma_50_Energy real,
  LoG_sigma_50_Entropy real,
  LoG_sigma_50_Kurtosis real,
  LoG_sigma_50_Maximum real,
  LoG_sigma_50_Mean real,
  LoG_sigma_50_MeanDeviation real,
  LoG_sigma_50_Median real,
  LoG_sigma_50_Minimum real,
  LoG_sigma_50_Range real,
  LoG_sigma_50_RootMeanSquared real,
  LoG_sigma_50_Skewness real,
  LoG_sigma_50_StandardDeviation real,
  LoG_sigma_50_TotalEnergy real,
  LoG_sigma_50_Uniformity real,
  LoG_sigma_50_Variance real,
  Mean real,
  Autocorrelation real,
  ClusterProminence real,
  ClusterShade real,
  ClusterTendency real,
  Contrast real,
  Correlation real,
  DifferenceEntropy real,
  Dissimilarity real,
  Energy real,
  Entropy real,
  Homogeneity1 real,
  Homogeneity2 real,
  Idmn real,
  Idn real,
  Imc1 real,
  Imc2 real,
  InverseVariance real,
  MaximumProbability real,
  SumAverage real,
  SumEntropy real,
  SumSquares real,
  SumSquares2 real,
  SumVariance real,
  SumVariance2 real,
  HighIntensityEmphasis real,
  HighIntensityLargeAreaEmphasis real,
  HighIntensitySmallAreaEmphasis real,
  IntensityVariability real,
  LargeAreaEmphasis real,
  LowIntensityEmphasis real,
  LowIntensityLargeAreaEmphasis real,
  LowIntensitySmallAreaEmphasis real,
  SizeZoneVariability real,
  SmallAreaEmphasis real,
  ZonePercentage real,
  GrayLevelNonUniformity real,
  HighGrayLevelRunEmphasis real,
  LongRunEmphasis real,
  LongRunHighGrayLevelEmphasis real,
  LongRunLowGrayLevelEmphasis real,
  LowGrayLevelRunEmphasis real,
  RunLengthNonUniformity real,
  RunPercentage real,
  ShortRunEmphasis real,
  ShortRunHighGrayLevelEmphasis real,
  ShortRunLowGrayLevelEmphasis real,
  Compactness1 real,
  Compactness2 real,
  Maximum3DDiameter real,
  SphericalDisproportion real,
  Sphericity real,
  SurfaceArea real,
  SurfaceVolumeRatio real,
  Volume real
  );

EOF
tableinfo=" "
for table in measures nodules reads series errors features; do
    tableinfo+=$(sqlite3 -separator : $DB "pragma table_info($table)" | tail -n +1 | awk -F':' '{print " ", $2}'  )
done
# Remove uid, including at the beginning of the string
tableinfo=$(echo $tableinfo | sed 's/[[:space:]]uid//g' | sed 's/^uid//g')
sqlite3 $DB "delete from errors;"
}

function fullPath {
    echo "$(cd "$(dirname "$1")"; pwd)/$(basename "$1")"
}

main "$@"
