baseurl: ""
languageCode: "en-us"
title: "LIDCTooling"
pluralizelisttitles: "false"

# Make all URLs relative, very handy
relativeURLS: "true"

# Menus
menu:
  main:
    - Name: "Building"
      Weight: -100
      URL: "/building/"
    - Name: "Usage"
      Weight: -90
      URL: "/usage/"
